spring.cloud.stream:
  function:
    definition: jokeProcessor
  bindings:
    domainProcessor-in-0:
      destination: jokes
    domainProcessor-out-0:
      destination: safe-joke
  kafka:
    bindings:
      domainProcessor-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      domainProcessor-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
    binder:
      brokers:
        - 127.0.0.1:9092